apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.cassandra.clusters.michael.configMap }}
data:
  CASSANDRA_CLUSTER_NAME: '{{ .Values.cassandra.clusters.michael.name }}'
  CASSANDRA_TRANSPORT_PORT_NUMBER: '{{ .Values.cassandra.ports.transport }}'
  CASSANDRA_PASSWORD_SEEDER: 'yes'