apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cassandra.clusters.alex.secrets }}
type: Opaque
data:
  CASSANDRA_USER: {{ .Values.cassandra.clusters.alex.auth.username | b64enc | quote}}
  CASSANDRA_PASSWORD: {{ .Values.cassandra.clusters.alex.auth.password | b64enc | quote}}