apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.cassandra.clusters.alex.name }}-proxy'
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    {{- include "apache-cassandra.selectorLabels" . | nindent 4 }}
    component: {{ .Values.cassandra.clusters.alex.name }}
  ports:
    - name: '{{ .Values.cassandra.clusters.alex.name }}-proxy'
      port: {{ .Values.cassandra.clusters.alex.ports.client }}
      targetPort: {{ .Values.cassandra.ports.client }}