apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.cassandra.clusters.michael.name }}-proxy'
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    {{- include "apache-cassandra.selectorLabels" . | nindent 4 }}
    component: {{ .Values.cassandra.clusters.michael.name }}
  ports:
    - name: '{{ .Values.cassandra.clusters.michael.name }}-proxy'
      port: {{ .Values.cassandra.clusters.michael.ports.client }}
      targetPort: {{ .Values.cassandra.ports.client }}