apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafka.host }}
spec:
  type: ClusterIP
  selector:
    {{- include "apache-kafka.selectorLabels" . | nindent 4 }}
    component: {{ .Values.kafka.name }}
  ports:
    - name: '{{ .Values.kafka.name }}-listener-port'
      port: {{ .Values.kafka.ports.k8 }}
      targetPort: {{ .Values.kafka.ports.container }}