apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.kafka.name }}-listener-proxy'
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  clusterIP: {{ .Values.kafka.ip }}
  selector:
    {{- include "apache-kafka.selectorLabels" . | nindent 4 }}
    component: {{ .Values.kafka.name }}
  ports:
    - name: '{{ .Values.kafka.name }}-listener-proxy'
      port: {{ .Values.kafka.ports.node }}
      targetPort: {{ .Values.kafka.ports.container }}