apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kafka.secrets }}
type: Opaque
data:
  ALLOW_PLAINTEXT_LISTENER: 'eWVz'
  KAFKA_ZOOKEEPER_CONNECT: 'MTI3LjAuMC4xOjIxODE='
  KAFKA_CFG_ADVERTISED_LISTENERS: 'UExBSU5URVhUOi8vbG9jYWxob3N0OjkwOTI='
  KAFKA_CFG_LISTENERS: 'UExBSU5URVhUOi8vOjkwOTI='
  KAFKA_BROKER_ID: 'MQ=='